### ISSUE TITLE
[Feature] Allow players to summon by Gm request

### ISSUE THREAD

**Issue by emomgo3** [trioderegion/warpgate#101]
Is it plausible to implement a feature which enables players to summon companions with GM permission instead of giving players all Permissions needed for summoning?
As far as i know https://github.com/MrVauxs/pf2e-jb2a-macros "Summon Anything" macro uses the Warpgate API but doesnt require the players to possess extra permissions by simply asking for gm approval. I'd like it if it were possible to allows my players to summon without allowing them, for example, to edit the configs of their tokens.

The feature as it exists in the jb2a macros.

![image](https://user-images.githubusercontent.com/48028314/204654580-88badd17-682b-40c8-820d-6eadfefe0881.png)

**Comment by trioderegion** [comment]
This could be supported by leaning on the current `PLACEMENT` event. By pushing the permissions check into the core `spawnAt`, I could allow the initial spawning operation (placing the crosshairs to determine location) to check if it has all required permissions and to flag the `PLACEMENT` event data with the `spawn` arguments (or a subset), for the GM to handle.

This does complicate the spawning callback functionality, but recent advancements in my approach has made that a little more manageable now.
