### ISSUE TITLE
`comparisonKey` being `id` throws a less than helpful error with multiple applications of the same data

### ISSUE THREAD

**Issue by krbz999** [trioderegion/warpgate#108]
To reproduce:
```js
const effect = {label: "Steve", icon: "icons/magic/holy/meditation-chi-focus-blue.webp"}
const options = {comparisonKeys: {ActiveEffect: "id"}};
const updates = {embedded: {ActiveEffect: {[randomID()]: effect}}};
for(let i = 0; i < 10; i++) await warpgate.mutate(token.document, updates, {}, options);
```

**Comment by GamerFlix** [comment]
This is not even with multiple applications as far as I can tell. A single mutation with a comparison key of `id` or `_id` simply throws a model validation error saying the _id is invalid.

**Comment by trioderegion** [comment]
Previously seen error messages have been corrected or I am otherwise unable to reproduce the error in the working v1.16 codebase.

10 mutations are applied, all with identical data -- no errors observed.
