### ISSUE TITLE
Can't originate crosshairs on existing template icon and can't pan map

### ISSUE THREAD

**Issue by dmrickey** [trioderegion/warpgate#110]
These are from memory because I haven't tested in a while and am updating my app without access to my server, but from notes I left myself a while ago these are two problems with Crosshair's current implementation.

- Current control icons for templates are still being drawn while crosshairs is active, meaning it's basically impossible to select a spot on the map underneath one of those control icons as the control icon captures the mouse click.
- If a user tries to pan a map while crosshairs is active, it immediately completes -- a couple possible example implementation to illustrate/clarify what I mean
  - the click is only committed if a timer determines that it's a click and not a press and hold. If it's a press and hold, then the user is probably doing another action
  - if mouse down and mouse up are detected in the same spot, then that's a click and can be committed, but if the user clicked down and then clicked up elsewhere on the map, then they're probably doing another action.

**Comment by dmrickey** [comment]
This is what I ended up doing for the first bullet point.

```
            // disable existing templates' control icon buttons to allow placing templates on top of other templates
            const existingTemplates = canvas.templates.placeables;
            existingTemplates.forEach(existing => {
                if (existing.controlIcon) {
                    existing.controlIcon.removeAllListeners();
                }
            });

            // crosshairs stuff

            // redraw the templates layer to turn control icons back on
            await canvas.templates.draw();

**Comment by trioderegion** [comment]
Interestingly, `CanvasLayer#interactiveChildren` is a r/w property that controls...if any children on that layer can be interacted with. Setting this to false while crosshairs is in flight ended up being a simple and elegant solution :)

[crosshairs_window_controls.webm](https://user-images.githubusercontent.com/14878515/213954593-a76865ba-5950-4048-9506-f0f63d23aeb3.webm)
