### ISSUE TITLE
Exception (sometimes) in foundry.js with spawnAt - Token `bars` missing

### ISSUE THREAD

**Issue by pmoore603** [trioderegion/warpgate#112]
Not sure if there is a better way to seek help, please let me know if there is a better way to get assistance.

I am helping out with SWADE Immersive macros, and I'm seeing this exception with a shape changer macro.  The macro basically creates a new actor based off a preset actor in a specific folder, and copies the actor info to it.  The macro uses warpgate to create a new token and removes the old one.  Here is the call to spawnAt:

```
        let newTokenId = await warpgate.spawnAt(token.center, actor.name, {
            token : {
                alpha : SWIM.ALMOST_INVISIBLE,
                actorId : actor.id,
                texture : {
                    'scaleX' : scaleX,
                    'scaleY' : scaleY,
                }
            }
            } );
```

Unfortunately, it doesn't occur all the time.... perhaps 25% of the time.

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'bar1')
[Detected 3 packages: system:swade, warpgate, swim]
    at foundry.js:46377:28
    at Array.forEach (<anonymous>)
    at Token.drawBars (foundry.js:46376:22)
    at TokenDocument._onUpdateBaseActor (foundry.js:22406:19)
    at SwadeActor._onUpdate (foundry.js:16680:9)
    at SwadeActor._onUpdate (SwadeActor.ts:1258:11)
    at ClientDatabaseBackend.callback (foundry.js:12823:11)
    at foundry.js:12766:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateDocuments (foundry.js:12766:33)
    at ClientDatabaseBackend._updateDocuments (foundry.js:12639:17)
    at async SwadeActor.updateDocuments (commons.js:6153:23)
    at async SwadeActor.update (commons.js:6250:23)
    at async Mutator._updateActor (mutator.js:291:24)
    at async Object._spawnAt [as spawnAt] (api.js:544:7)
    at async replaceToken (shape_changer.js:405:26)
    at async main (shape_changer.js:188:13)
```

In foundry, it is failing at the first line of the `forEach`.  Obviously, `this.bars` is undefined.
    
```
drawBars() {
    if ( !this.actor || (this.document.displayBars === CONST.TOKEN_DISPLAY_MODES.NONE) ) {
      return this.bars.visible = false;
    }
    ["bar1", "bar2"].forEach((b, i) => {
      const bar = this.bars[b];
      const attr = this.document.getBarAttribute(b);
      if ( !attr || (attr.type !== "bar") ) return bar.visible = false;
      this._drawBar(i, bar, attr);
      bar.visible = true;
    });
    this.bars.visible = this._canViewMode(this.document.displayBars);
  }
```

If I slap `if (!this.bars) { return; }` before the forEach and save foundry.js, it works.

Any thoughts?

**Comment by pmoore603** [comment]
During debug, I discovered the following.

In foundry, during post token creation, it calls `doc._onCreate` followed by all the `createToken` callbacks (see foundry snipped below).  The callbacks seem to finish rather quickly, but the `doc._onCreate` can be delayed.  And it seems that this is where the token `bars` is initialized.  The `bars` creation is finishing asynchronously, and occasionally AFTER drawing the token takes place, which is what causes the exception in Foundry.  I solved the issue by putting a 25ms sleep after the call to `Gateway._spawnTokenAtLocation` in api.js.  Not the best approach, it works.  Something somewhere along the line (may or may not even be in warpgate... could be in lib-wrapper?) is probably not doing an `await`.

```
_postCreateDocumentCallbacks(type, collection, result, {options, userId, parent, pack}) {
    const cls = getDocumentClass(type);
    const callback = (doc, data) => {
      doc._onCreate(data, options, userId);
      Hooks.callAll(`create${type}`, doc, options, userId);
      return doc;
    };
    ... <snip> ...
}
```
My solution, added this function to `api`:
```
  static sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
```
And add the sleep here, in `api.js`:
```
      /** @type Object */
      const spawnedTokenDoc = (await Gateway._spawnTokenAtLocation(protoData,
           spawnLocation,
           options.collision ?? (options.duplicates > 1)))[0];
      createdIds.push(spawnedTokenDoc.id);
      logger.debug('Spawned token with data: ', MODULE.isV10 ? spawnedTokenDoc : spawnedTokenDoc.data);
      await api.sleep(25);
      await Mutator._updateActor(spawnedTokenDoc.actor, updates, options.comparisonKeys ?? {});
```

**Comment by trioderegion** [comment]
v1.16 includes more locations where the token texture is preloaded, which potentially addresses this issue.

Additionally, Warp Gate's options already includes a configurable delay that accomplishes basically the same thing you have derived.
