### ISSUE TITLE
[Feature] Optional parameter for `crosshairs.collect()` to get entities the crosshair touches.

### ISSUE THREAD

**Issue by SalieriC** [trioderegion/warpgate#121]
Currently `crosshairs.collect()` can return tokens that are _affected_ by a template. This might be sufficient for most systems but some systems could profit from an optional modifier that returns all tokens that are on a tile which is _touched_ by a template. An example would be the SWADE system in which all tokens are affected as long as the template merely  touches the tile on which the token is on.

**Comment by trioderegion** [comment]
Currently, you can pass an arbitrary filter function to the collection function (third argument): https://trioderegion.github.io/warpgate/warpgate.crosshairs.html#.collectPlaceables

This collect function is left purposefully simple and it is intended to be customized for specific purposes.

That said, its not impossible, but will remain low priority for the time being.

**Comment by trioderegion** [comment]
I did misread originally -- asking crosshairs to "chain derive" containment is well outside the scope of warpgate's functionality. The filter function is what you will want to use -- define your filter function based on whatever metrics you need.
