### ISSUE TITLE
Token Mold vs. Warpgate

### ISSUE THREAD

**Issue by MrVauxs** [trioderegion/warpgate#123]
I had reports of users trying to use PF2e Animations summon feature with Token Mold enabled.
This module conflict causes the token data to be practically overwritten by Token Mold, resulting in this:
![image](https://user-images.githubusercontent.com/32039708/220753789-1e3d89db-8bf4-4a53-9536-90745ca256fd.png)

(The token should be called "Eagle", and the token should be the same as the actor image)

**Comment by trioderegion** [comment]
I cannot address changes done by other modules after warpgate has created the tokens.
