### ISSUE TITLE
UX Feature: Timeout before canvas pan on crosshairs.

### ISSUE THREAD

**Issue by SalieriC** [trioderegion/warpgate#126]
Showing crosshairs seems to pan the canvas towards the mouse on activation. This can get a little funky when it is activated from a macro that is clicked as the canvas then pans down, causing some irritation and - on canvas that is zoomed in quite a bit - potentially pans the desired target away. This doesn't happen when the macro is executed using a hotkey of course but for mouse users like myself this can get a little frustrating.

One idea to prevent this would be a short timeout before the pan occurs. A second or two should be plenty to get the mouse back up, hopefully without interfering with other functionalities that need the pan.

**Comment by trioderegion** [comment]
That is indeed a bit frustrating. Subtle. Thanks for the report!
