### ISSUE TITLE
Can't update to 1.17.0

### ISSUE THREAD

**Issue by InjustFr** [trioderegion/warpgate#134]
Hi

Updating warpgate to the latest version isn't possible, it crashes at installation

The returned error message is: "Metadata validation failed for module "warpgate": The file "scripts\warpgate.js" included by module warpgate does not exist"

I've tried uninstalling and reinstalling a fresh version and it still fails  with the following error message: "Error: Cannot read properties of null (reading 'protected')"

**Comment by alexdiste** [comment]
I already warned the creator but meanwhile I will provide you a workaround. Change module.json changing all occurence of \\ with / and it will work.

This the correct module.json
{
    "title": "Warp Gate",
    "id": "warpgate",
    "esmodules": [
        "scripts/warpgate.js"
    ],
    "styles": [],
    "languages": [
        {
            "lang": "ja",
            "name": "Japanese",
            "path": "lang/ja.json"
        },
        {
            "lang": "fr",
            "name": "French",
            "path": "lang/fr.json"
        },
        {
            "lang": "en",
            "name": "English",
            "path": "lang/en.json"
        },
        {
            "lang": "de",
            "name": "German",
            "path": "lang/de.json"
        }
    ],
    "externals": [],
    "compatibility": {
        "minimum": "10",
        "verified": "11.300"
    },
    "relationships": {
        "systems": [],
        "modules": []
    },
    "description": "Utility module providing system-agnostic functions for creating and modifying tokens, p2p \"hooks\", lookup helpers, and more.",
    "version": "1.17.0",
    "authors": [
        {
            "name": "honeybadger",
            "url": "https://github.com/trioderegion"
        }
    ],
    "url": "https://github.com/trioderegion/warpgate",
    "manifest": "https://github.com/trioderegion/warpgate/releases/latest/download/module.json",
    "download": "https://github.com/trioderegion/warpgate/releases/download/1.17.0/module.zip"
}

**Comment by InjustFr** [comment]
Yes, I've noticed that we posted at the same time, it was a funny coincidence ;)
Thanks for the workaround, reading your issue helped me
