### ISSUE TITLE
PF2e Animations Summons not sending token requests to DM

### ISSUE THREAD

**Issue by ImNotYourBudde** [trioderegion/warpgate#135]
With the newest update when players try to summon anything from a spell or ability and it asks them to place a token and send a confirmation to the DM to accept the token summon, nothing pops up for the DM. If the DM casts the spell or ability for the player everything works correctly. Its only if connected players attempt. Rolled back to 1.16.2 and everything works again.

**Comment by ImNotYourBudde** [comment]
I re updated back to current to replicate the issue so I could screen grab the console and this is what happens both on the table top, in terms of a template being placed but no token, and the log of the errors when a player tries to summon a creature.
![Screenshot 2023-06-07 203804](https://github.com/trioderegion/warpgate/assets/135798110/fe98a1a3-bba3-4ce8-9d35-8cc41490cacc)

**Comment by trioderegion** [comment]
I'm not seeing any warpgate errors here. Just a sequencer error. I'm not quite sure how to help 😅

**Comment by ImNotYourBudde** [comment]
Hmm, I wonder why rolling back fixes it. But fair enough! Thanks for looking at it! I will try and get over there and see if I can figure this thing out, because I'm not the only one having this issue.

**Comment by trioderegion** [comment]
Which version of foundry are you on? Forgot to ask.

**Comment by trioderegion** [comment]
This is a stab in the dark, but try this version: https://github.com/trioderegion/warpgate/releases/download/1.17.%2B2.1/module.json

**Comment by trioderegion** [comment]
Tagging @MrVauxs from [MrVauxs/pf2e-jb2a-macros](https://github.com/MrVauxs/pf2e-jb2a-macros) for visibility and troubleshooting.

1.17.+2.1 (linked above) *should* be better, but I really have no idea where its breaking down :(

**Comment by MrVauxs** [comment]
For some bizarre reason `warpgate.event` now does not get actually tunneled through to the GM.
![image](https://github.com/trioderegion/warpgate/assets/32039708/d86813de-3dce-4868-b384-7da3b5c90426)

**Comment by trioderegion** [comment]
This was the missing piece of the puzzle. I believe this is a product of the development bundling tool introduced in 1.17. Reproduced reliably.

**Comment by MrVauxs** [comment]
btw this is fixed now kthx
