### ISSUE TITLE
[Feature Request] Make crosshairs visible to other players

### ISSUE THREAD

**Issue by this-gavagai** [trioderegion/warpgate#139]
I don't know if this is at all possible with the MeasuredTemplate object, but it would be extremely useful if it were possible for other players to see the crosshairs while being moved around before being placed. Does Foundry provide the right hooks to make this possible?

**Comment by trioderegion** [comment]
To my knowledge, foundry does not natively provide a way to show temporary documents (crosshairs). However, the desire to do so has come up in the past.

I can't promise anything in the near future, but I'll see what I can do.

**Comment by this-gavagai** [comment]
Thanks @trioderegion! This is a great module and it has improved my games significantly. I really appreciate the work you do for it.
