### ISSUE TITLE
Remove array prototype patch

### ISSUE THREAD

**Issue by trioderegion** [trioderegion/warpgate#145]
https://github.com/trioderegion/warpgate/blob/fffae84f57533e328a72d7738e0f7b697bb0f910/scripts/events.js#L11

Turn into free function.

**Comment by deurk** [comment]
This, really. You're breaking some systems/plugins that rely on `Array` loops.

**Comment by trioderegion** [comment]
I was only made aware of this issue in early September, despite it being present day 0 and commonly known as an issue in the pf2e community.

I literally just didn't know, and will address it.

**Comment by deurk** [comment]
Thanks 👍🏼
