### ISSUE TITLE
Duplication mutation name detected

### ISSUE THREAD

**Issue by Iceman11691** [trioderegion/warpgate#146]
I am not sure how to fix this problem.  It occurs when I put on hunter's mark or rage.  I am not sure what settings I have to change.  Can you help?

**Comment by trioderegion** [comment]
This typically indicates that you have already applied that mutation to the actor once already. If this is intended, and you need to keep the same mutation name, perform a revert of that mutation name first, then apply the mutation.

If the mutation is not on the actor already, the revert function will do nothing (i.e. its safe to use).
