### ISSUE TITLE
[Issue] Preventing PDF to Foundry Importer from functioning, PF2e module

### ISSUE THREAD

**Issue by Malkyn99** [trioderegion/warpgate#150]
Title. According to Find the Culprit, Warp Gate is causing PDF to Foundry Importer to not function. Pulls up the window, I select my pdf and hit Import and nothing happens. Able to work around it by disabling Warp Gate, importing everything, and then re-enabling, but wanted to advise

**Comment by trioderegion** [comment]
Dupe of #145
