### ISSUE TITLE
Template layer breaks if crosshair is spawned right after template is created 

### ISSUE THREAD

**Issue by Haxxer** [trioderegion/warpgate#151]
If a template is created right before a crosshair is spawned, the template layer breaks because it has been switched to before the template's drawing has been fully rendered.

```js
const templateData = {
    t: "cone",
    distance: 15,
    fillColor: '#000000',
    angle: 90,
    direction: 45, x: 0, y: 0,
    user: game.user.id
}

let template = (await canvas.scene.createEmbeddedDocuments('MeasuredTemplate', [templateData]))[0];

const rotateCrosshairs = await warpgate.crosshairs.show(
    {
        drawIcon: false,
        drawOutline: false,
    });
```

The above macro causes this error:

![image](https://github.com/trioderegion/warpgate/assets/12858387/ad4a86f7-493d-4a6c-878a-855e51363500)

**Comment by trioderegion** [comment]
Hmm, both myself and devNumbers are unable to reproduce this behavior. Is it dependent on a certain layer being active prior to this script? Incidentally, I have found a niche issue where if you swap the layers while crosshairs is active, my handlers are orphaned and throw errors until refresh.

**Comment by Haxxer** [comment]
If you are on the token layer, and run the macro, I can get the error.

**Comment by trioderegion** [comment]
Could I bother you to try 11.313 (latest)? I could be making things up, but I feel like there were some canvas/rendering fixes(?) or at least modifications at some point in v11.

**Comment by Haxxer** [comment]
I can confirm that this is no longer an issue on 11.313 - apologies for the waste of time!
