### ISSUE TITLE
[Feature request: Grid highlighting] - Creating arbirtary sized rings

### ISSUE THREAD

**Issue by thatlonelybugbear** [trioderegion/warpgate#154]
Support for `options.size` being an array of sizes to resize each ring as needed.

**Comment by trioderegion** [comment]
As I refactor the `options.color` option to accept a Function that generates the color based on the current grid-square info (x, y, and ring number), I am coming to the realization that `options.size` was doing double-duty. We will keep `size` as an optional multiplier for how many single rings make up a user-side "ring", and expand `rings` to accept a list of band sizes.

Would the following be an acceptable, user-side, approach for achieving this issue's overall purpose? `rings` now accepts a list of values, where each value defines how many "single rings" make it up.

```js
const name = 'rangefinder';

// repeat the pattern 'green, yellow, empty, green, yellow, empty'
const colors = ['green','yellow',false];

// making 4 total rings where each ring is made of up 'size' single rings
const rings = [1,2,1,2]; 

// Size of each set of rings
const size = 2;

const highlights = warpgate.grid.highlightRing(
    {x: token.x, y:token.y, rings, name}, 
    {colors, size});
```
