### ISSUE TITLE
Apply all Chris's Premades Issue

### ISSUE THREAD

**Issue by Aiacos** [trioderegion/warpgate#159]
Hi, 
Apply all Chris's Premades Automations cause some spell to break with errors in attachments
Thanks,
L.
![enable](https://github.com/trioderegion/warpgate/assets/1658617/1c744f16-f508-4d4b-9f8d-4ae064564776)
![Issue](https://github.com/trioderegion/warpgate/assets/1658617/9e6dc28c-c228-41ad-a028-7ac25d98c1cd)

**Comment by trioderegion** [comment]
This is an issue with Chris' Premades, not warpgate.
