### ISSUE TITLE
Tidy 5e Sheets Rewrite compatibility

### ISSUE THREAD

**Issue by kgar** [trioderegion/warpgate#161]
Hello, I am working on a rewrite of the dnd5e Tidy 5e Sheets module ([new version here](<https://github.com/kgar/foundry-vtt-tidy-5e-sheets/>)), and I am building it with svelte. As a result, my sheets do not call the `renderActorSheet` hook very often, since the sheets largely rely on fine-grained reactivity. However, I see that this hook is integral to warpgate's Revert feature and maybe others.

![image](https://github.com/trioderegion/warpgate/assets/4632129/6c6006a9-dcae-4d37-800f-64c827d1f1f9)

warpgate is system agnostic, but is there any possibility of us working together to make a compatible solution between my sheets and this module? I can provide API functions, custom hooks, alternate locations for the Revert option, and/or some other option.

**Comment by trioderegion** [comment]
I can provide guidance for how to insert my functionality into your applications, but warpgate is and will always be targeted at the standard Foundry API -- any extensions need to hook into those standard workflows.

**Comment by kgar** [comment]
Thanks for replying.

I do not have the choice of calling the standard render hook on each render cycle, because my sheet is not a FormApplication V1 style sheet that runs on Handlebars. It is FormApplication V2 style, in as much as it can be before Foundry V12 drops. For that reason, the standard sheet render hook is not going to work for me. After the initial render, reactivity is in the hands of my chosen web tech, and I provide my own hooks where able. You may see more of this when other form applications go V2 in the future.

For warpgate, I can subscribe to the appropriate hook on my side and call warpgate code when it is present, if that is an option. Do you have a recommended way for my module to call into warpgate to keep the window header up-to-date? Is there an available API?

**Comment by trioderegion** [comment]
There is not currently a good api for it. However, I am working on a larger refactor, so this is good timing.

A `showRevertDialog` style function would make sense to expose, and on actor updates potentially rerender a button or similar on your sheet? 

If I am not already, i should be hooking into the `getHeaderButtons` hook to add my button, and it would get updated data when you call that hook manually. I might be able to patch that relatively quickly if it could help at all.

As far as the v12 reworks are concerned, i'll be keeping my eye on it, but warpgate should only rarely add UI elements, due to this specific issue - ha. However I do it, it will certainly follow the foundry patterns as best as possible.

I'm hoping to coincide updates with v12 stable, as a rough time scale.

**Comment by kgar** [comment]
Normally, `getHeaderButtons` only triggers on initial or forced / full renders, which has always been a little perplexing to me.

If I'm able to trigger the outer window render manually and there aren't any performance issues, then I'm glad to call `getHeaderButtons` more often. I'll do some study on my side to see what my options are.

**Comment by kgar** [comment]
After looking it over, it would be too much of a lift to completely refresh the window header on each render. That is what would be required if I were to use the `getHeaderButtons` hook to acquire the latest header buttons. There is some copying of Foundry code among other things that will be very brittle. It would also lock out any other authors who adjust the header on render.

Would it be possible to have a refresh-style API function which can be called that would ensure that the warpgate header content is whatever it should be in that moment in time? I could call that refresh function each time there would have been a `renderActorSheet` hook call in a traditional form application, when the warpgate module is active.

**Comment by trioderegion** [comment]
> As far as I can tell, I just need to be able to call `UserInterface._renderActorSheet(...)` from outside of warpgate, or a more public-facing API equivalent of this.

I was likely overcomplicating the issue, heh. I can absolutely do this and should have time near the end of the week to get something in place for you. Keep an eye out for a mention in a PR with a proposal.

**Comment by kgar** [comment]
By the way, this whole process has had the benefit of getting me familiar with all kinds of modules.

Warpgate is super cool! It gets DM creativity flowing, the wiki is really useful for helping with trying out the stuff, and I can only imagine what other module devs are doing with it. ✨

**Comment by kgar** [comment]
I had to do some integration on my side for PopOut! recently as well, because I switched to the floating context menu in the style of dnd5e 3.0.x.

So, I've got the scaffolding ready for whenever I'm able to call that warpgate API function for applying the correct buttons on the window header.
