### ISSUE TITLE
Container Item Removal Support

### ISSUE THREAD

**Issue by chrisk123999** [trioderegion/warpgate#162]
Currently when an warpgate mutation removes a container, all the items inside get removed from the container and show up on the sheet. Reverting the mutation results in the container coming back, but none of the items returning to the container.

**Comment by trioderegion** [comment]
If the system you are using provides create/update/delete options to modify how containers are handled when manipulated, you can pass them into the updateOpts. Otherwise, I'm not sure warpgate can do anything about this as the container concept is system specific.

**Comment by trioderegion** [comment]
Talked to Kim a bit and he pointed me to a `deleteContents` option. Try passing that with value `true` in `updateOpts.embedded.Item`.

This only addresses one part of the larger issue, but its a start!
