### ISSUE TITLE
[Feature request] Support for wildcard image

### ISSUE THREAD

**Issue by DarKDinDoN** [trioderegion/warpgate#2]
Hello,

Currently, warpgate doesn't seem to support tokens with wildcard images.

Example from jb2a dancing lights token:
![image](https://user-images.githubusercontent.com/1687854/128265182-cbee456b-6f78-46e1-96bd-41a9a7ca04d2.png)

**Comment by trioderegion** [comment]
Should be good to go in 1.1.2!
