### ISSUE TITLE
Allow more crosshairs shapes

### ISSUE THREAD

**Issue by trioderegion** [trioderegion/warpgate#22]
Consider expanding crosshairs to support more shapes -- squares and lines are a good start.

Many issues to consider when doing this -- this is LOW PRIORITY.

**Comment by trioderegion** [comment]
Why am I being silly -- just draw the borders according to desired shape, while leaving "origin" in the center.

**Comment by dmrickey** [comment]
Yeah having a square would be nice. I'm trying to "select a square on the map" and it would be nice to have the outline be a square to show selection rather than a circle

**Comment by trioderegion** [comment]
For now, the basic functionality is provided in v11 with a config field `t` following the same field in MeasuredTemplateDocuments.
