### ISSUE TITLE
Config option for non-resizeable targeting

### ISSUE THREAD

**Issue by dmrickey** [trioderegion/warpgate#26]
For example, if I'm using Crosshairs to select a specific square on the grid, or am casting a fireball, those are fixed sizes so it would be nice to turn off template resizing. Maybe something like `{ fixed: true }` where it defaults to `false`. Or maybed `fixedSize` or something like that

**Comment by trioderegion** [comment]
Reasonable request. Its likely that a fixed size should be the default anyway.
