### ISSUE TITLE
Module not loading properly

### ISSUE THREAD

**Issue by Robinhoodjun** [trioderegion/warpgate#3]
Hi,

When launching a world the following error occurs:
![Warpgate error](https://user-images.githubusercontent.com/88480417/128312909-4555f531-e0c4-4acf-b317-b47f26480cfc.png)

The module is installed here: /var/www/vhosts/dnd/foundry_vtt/data/Data/modules/warpgate

Thank you.

**Comment by trioderegion** [comment]
Yea, I was trying to be too fancy. I can correct this quickly. Sorry for the troubles.

**Comment by trioderegion** [comment]
Corrected in 1.1.3

**Comment by Robinhoodjun** [comment]
Works now, thank you for the quick help!
