### ISSUE TITLE
Expand utilities for working with warpgate data

### ISSUE THREAD

**Issue by Lazytron** [trioderegion/warpgate#36]
Currently checking if a given mutation exists is possibly by digging through the flags, but it would be handy to be able to quickly do a boolean check by name (or set of names)

Something like `warpgate.hasMutation(document, mutationName = "removeMe")` which returns boolean would be useful for cases where you want to revert a specific mutation by name if it exists.  

Alternative: an option to suppress errors and return early when calling revert with a name that doesn't exist (`{silent:true}` or something).

**Comment by trioderegion** [comment]
Both are solid ideas.  We could use some more utility functions like this in general. Depending on scope, may be a separate release.
