### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by Ikabodo** [trioderegion/warpgate#51]
I'm not 100% sure this is caused by warpgate, but culprit is pointing towards it so I'll post it here.
It seems warpgate is throwing this error:
![image](https://user-images.githubusercontent.com/7766890/152078419-80e09a0c-52c4-4f26-8438-05bd5ed13264.png)

It is thrown when reloading a page with an animated tile.

**Comment by trioderegion** [comment]
Warpgate has no play function or animation functions. Furthermore, the error is coming from a core file. As a guess, its something with Sequencer?
