### ISSUE TITLE
Add setting to optionally allow modules to override the "Always accept mutation requests setting"

### ISSUE THREAD

**Issue by GamerFlix** [trioderegion/warpgate#53]
Modules that make use of Warpgate's mutation system to apply changes to unowned actors currently prompt the same mutation request as macros using the system. As such a GM either has to automatically accept all mutation requests from both macros and modules, or manually click through both of them even if they would like to only automatically allow requests send by modules (or vice versa).
As such an additional setting to only automatically accept requests from modules would be desirable.

**Comment by trioderegion** [comment]
Closed by #89
