### ISSUE TITLE
Allow for batch mutation requests

### ISSUE THREAD

**Issue by GamerFlix** [trioderegion/warpgate#54]
If one wishes to apply the same mutation to multiple tokens they currently have to loop over each token, passing the request to warpgate and then continuing with the next. This causes multiple mutation request popups the GM has to accept. Adding a batchMutate function that allows passing of an array of token documents to apply the same mutation to would not only remove the nessecity of a loop but also potentially allow warpgate to only display a single mutation request message for all passed token documents, something that may be desirable should one not wish to automatically accept all mutation requests as per the warpgate setting.

**Comment by trioderegion** [comment]
Rolling this into the concept of linked mutations.

The "parent" mutation should batch up all linked requests ahead of time (before any unrolling) and send out a single event notification. All clients will inspect the message, decide if they should handle the mutation, and collate all mutation requests into a single dialog for inspection (or autoaccepted) if module controlled or user overriden).

From there, each mutation will be applied by that client individually.

For reverts. Same idea, the mutation is created from the stack, all linked MUIDs are gathered, and an event notification is sent out containing the MUIDs to revert. Each client will revive said mutations from the stack and unroll individually.

**Comment by trioderegion** [comment]
This is now much easier to implement with the toast/confirmation overrides and can be implemented as a helper in warpgate v1.
