### ISSUE TITLE
[Feature request] Multiple tokens at once

### ISSUE THREAD

**Issue by DarKDinDoN** [trioderegion/warpgate#6]
Hello,

When a character is using "Summon animals" or "Dancing lights" in 5e, they have to place multiple tokens.
Maybe this can be implemented in warpgate? Click once, place the first token, click another time and place the second token, and so on.
Right click and skip the current token to be placed on the canvas.

**Comment by trioderegion** [comment]
This is *technically* possible currently with clever callback chaining, but I agree that there should be a more direct method.

After looking into it a bit, it will require some internal re-arrangements, but it should be possible. I'm thinking that I can make the `spawn` function properly asynchronous so it can be awaited and looped as needed.

**Comment by DarKDinDoN** [comment]
@trioderegion thx!!
