### ISSUE TITLE
The Arcane Hand script in the wiki no longer works

### ISSUE THREAD

**Issue by Zamrod** [trioderegion/warpgate#60]
If you run the Arcane hand script (either the basic or advanced version) in the wiki, it gives errors:

```
logger.js:35 Warp Gate | ERROR |  Item Add data missing 'type' field. Was this supposed to be an Update instead? Double-check comparison keys and Item identifier.
```

**Comment by trioderegion** [comment]
Does your summoned actor have two items named "Clinched Fist" and  "Grasping Hand"? That is what the code is looking to scale.

**Comment by trioderegion** [comment]
Assuming issue has been addressed by user. Closing issue.
