### ISSUE TITLE
Detect incorrect player permissions and warn

### ISSUE THREAD

**Issue by trioderegion** [trioderegion/warpgate#61]
warpgate requires several permissions that are not default for "Player" level accounts.
  - create tokens and configure tokens

Detect if a user lacks these permissions and gracefully exit and warn.

**Comment by Jeznar** [comment]
I'd like to extend this issue to include the need for players to have permission to:

- Create Tokens
- Configure Tokens **and**
- Use File Browser

I was recently tripped up by lack of file browsing permission for my players and the error message: `You do not have permission to browse the host file system!` was only helpful after seeking guidance on Discord.  

My problem was resolved by checking the right box.
<img width="686" alt="WarpGate Permission" src="https://user-images.githubusercontent.com/95548360/172155616-69aeda82-91f8-431f-9537-83631e48013c.png">

**Comment by trioderegion** [comment]
Feedback when missing permissions. 
![image](https://user-images.githubusercontent.com/14878515/200182447-ef0d6da4-222e-407f-bff3-f15be262559e.png)
![image](https://user-images.githubusercontent.com/14878515/200182659-9b70d663-d8f4-4af2-b760-74c4b884e612.png)
