### ISSUE TITLE
[Feature Request] - suppress mutation notifications

### ISSUE THREAD

**Issue by dmrickey** [trioderegion/warpgate#65]
I'd like there to be an option to be able to suppress mutation notifications. Adding a property to the options input seems like a good way to do it. Possibly also an overall world setting as well to supply a global default (personally I like world settings so I can set things up so my players don't have to worry about it or see more info than they know what to do with).

Specifically I only care about hiding successes, I believe that if I tell "the thing" to do something and the thing "doesn't tell me it failed" that's enough for me. So success notifications are just white noise for me.

**Comment by Vauryx** [comment]
Seconded, an option to remove the UI notifications would be great

**Comment by trioderegion** [comment]
thanks for the bump! added to v2 milestone 😄

**Comment by trioderegion** [comment]
subset of #49
