### ISSUE TITLE
[BUG] Conflict with system DND35 and the 'mutate' function

### ISSUE THREAD

**Issue by p4535992** [trioderegion/warpgate#66]
After some tests I can confirm there is some strange behaviour when call the mutate function on the system DND35.
For some strange reason the token is been update again with the actor data after the mutation.

![dd](https://i.imgur.com/8eELLG2.gif)

unfortunately I do not know the system very well and I have not been able to enter into detail about the origin of the problem.
What I can say is that with PF2E and DND5E I have not replicated the problem with the same code.

**Comment by trioderegion** [comment]
Can you point me towards, or show an example of, the actual mutation being performed? This feels like an unexpected (to me) system operation. I'll look into it.

**Comment by trioderegion** [comment]
Turning on the debug logging option in warp gate's settings will spew lots of information as the update gets processed.

**Comment by p4535992** [comment]
After the talking with the DND35 developer on dicrod i decided to close the ticket because is not a module issue.
