### ISSUE TITLE
[DOCUMENTATION] Wrong signature in the documentation

### ISSUE THREAD

**Issue by DarKDinDoN** [trioderegion/warpgate#7]
Hello,

Tried the new features. That's awesome!!
For `buttonDialog`, example in the documentation doesn't work.

Made it working by passing:
`const data = {buttons: [{label: 'First Choice', value: {token {name: 'First'}}, {label: 'Second Choice', value: {token: {name: 'Second'}}}]}` (was also missing two quotes in the example)

**Comment by trioderegion** [comment]
Thanks for the catch!  :). It also looks like the `buttons` field is a bit redundant. Will consider changing that....maybe.
