### ISSUE TITLE
Version of warpgate.EVENT.REVERT that happens before full reversion

### ISSUE THREAD

**Issue by MrVauxs** [trioderegion/warpgate#72]
As the title suggests. It'd be great for "exit" animation purposes, as currently there can be a fair amount of staggering as the token changes images before the animation can appear to transform them into their original form.

**Comment by trioderegion** [comment]
My initial version did have a PRE_REVERT event, but I ended up removing it as I couldn't find a strong use case for it.  Could you explain this use case a little bit more? I'm assuming this is in a remote mutation scenario.

**Comment by MrVauxs** [comment]
The use-case is that when a person Reverts a token, an animation is played. Issue is, the revertion process is finished first, causing the animation to play AFTER the token has reverted.

The animation of course is one depicting the reversal from one state to the other. It happening after the reversal happened causes issues, like say when we change the token image from one state to the other, the token image changes first, then the animation happens.

Being able to have PRE_REVERT would allow people to make such exit animations smoother and actually logical.

**Comment by trioderegion** [comment]
gotchya, thanks for the explanation. The current method of remote mutations/reverts and they they interact with the event system doesn't let me add this stage very easily.

The in-development v2 will support this natively.

**Comment by trioderegion** [comment]
This will be included in the upcoming release.  Because the revert system uses the mutation system, the `EVENT.MUTATION` is effectively the same as the current `EVENT.REVERT_RESPONSE|MUTATION_RESPONSE`. I have moved this event to just before the revert/mutation is applied in the case of remote operations.

If this does not address your use-case, pleas re-open.
