### ISSUE TITLE
1.14.!0 beta Foundry v10 testing 5 - crosshairs zIndex error thrown

### ISSUE THREAD

**Issue by napolitanod** [trioderegion/warpgate#73]
I was testing the beta in v10 Foundry v10 testing 5. Adding this report should you not be aware of it as of yet:

This command warpgate.crosshairs.show({size: 2}) raises a zIndex error

foundry.js:29777 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'zIndex')
[Detected 1 package: warpgate]
    at foundry.js:29777
    at Array.reduce (<anonymous>)
    at TemplateLayer.getZIndex (foundry.js:29776)
    at TemplateLayer.activate (foundry.js:29718)
    at Crosshairs.drawPreview (crosshairs.js:318)
    at Object.showCrosshairs [as show] (gateway.js:113)
    at <anonymous>:1:21

**Comment by napolitanod** [comment]
(I am using Warpgate 1.14.!0)

**Comment by trioderegion** [comment]
I am unable to reproduce this error. Does this occur with all other modules disabled?

**Comment by napolitanod** [comment]
Damn it, yes, its another module (Sequencer) interacting with it. I dont think Sequencer is on 10 though mostly works aside from here. Sorry for the bother.

**Comment by trioderegion** [comment]
Its ok, the two modules are often found together and it still could be an error on my side (its happened before with sequencer). Please re-open if WG is suspected at all in this failure.
