### ISSUE TITLE
[v10] Collider's FUBAR

### ISSUE THREAD

**Issue by MrVauxs** [trioderegion/warpgate#77]
![image](https://user-images.githubusercontent.com/32039708/189564990-72429fdd-d1f4-49dc-8ffb-f7190fc3e2e8.png)

When using `duplicates:` or simply summoning tokens on top of one another with `collision:true`, Warpgate doesn't respect collision.
[Discord Link](https://discord.com/channels/772596237605011466/911717215705899029/1018714362216714250)

**Comment by daft-develop** [comment]
I encountered this issue as well testing my v10 migration for the Dnd5e system. Couple extra notes that might help:

- Testing warpgate v1.14.0 on both foundry v9.280 (dnd5e 1.6.3) and v10.288 (dnd5e v2.0.3)
- No other modules active, blank scene, and try to spawn at least a few tiles away from caster
- Added a couple walls to test spawning near walls or in a big empty area
- Using macro `warpgate.spawn("Skeleton",{},{},{duplicates:10})` with Skeleton in actor list
- Collision *mostly* works in v9, but fails every time in v10 - failure here meaning all tokens on top of each other

Pretty sure this is a problem with the return check at the end of canFit in propogator.js (line 69), I think checkCollision behaviour changed between v9 and v10.

If I run the dummy collision, `canvas.walls.checkCollision(new Ray({x:100,y:100},{x:200,y:200}))` in v9, it returns false, but in v10 it returns an empty array (I assume if there is a collision, the array is populated with any "hits"). This jives with the API docs:

v9 - https://foundryvtt.com/api/v9/WallsLayer.html#checkCollision
v10 - https://foundryvtt.com/api/v10/classes/client.WallsLayer.html#checkCollision

so maybe another `game.release.generation < 10` or `MODULE.isV10` type check as part of canFit's return?

**SIDE NOTE**
Testing in v9, it was still complaining about collisions if I tried to spawn directly against a wall. If I inset the wall off the grid a bit, it has no trouble. Might just need to reduce the ray length to 99% or something to avoid the 1 pixel overlap.

_Works Fine_
![works in v9](https://user-images.githubusercontent.com/59496570/195764661-002bd041-d13a-414a-8be1-dcce1f22ec1b.png)

_Does Not Work_
![pileup in v9](https://user-images.githubusercontent.com/59496570/195764833-3db18348-cb86-4a96-837e-b56f21966bb3.png)

**Comment by daft-develop** [comment]
There's maybe a related foundry core bug on this: https://github.com/foundryvtt/foundryvtt/issues/8257#issue-1382998199.
In case you're finding that checkCollision is always returning an empty array in v10.

**Comment by daft-develop** [comment]
`canvas.walls.checkCollision(new Ray({x:...,y:...},{x:...,y:...}), {mode:"any", type:"sight"})` seems to do the trick for v10. It returns a boolean with mode "any", but it seems to limit it's check to visible walls only (type "sight").

**Comment by trioderegion** [comment]
Thanks for the investigation -- it really helps a lot and gives me a solid place to start digging. I should be able to dig into this in the upcoming week!

**Comment by Haxxer** [comment]
All this needs to be fixed is to change this line:
https://github.com/trioderegion/warpgate/blob/master/scripts/propagator.js#L69
to:
```js
return !collision || !canvas.walls.checkCollision(new Ray(origin, {x:position.x+tokenData.width*canvas.scene.dimensions.size/2,y:position.y+tokenData.height*canvas.scene.dimensions.size/2})).length;
    }
}
```
