### ISSUE TITLE
PF2E Eidolon Token Problem

### ISSUE THREAD

**Issue by Armandeus66** [trioderegion/warpgate#79]
Since installing Warp Gate, whenever I load Foundry, an eidolon token that was already on the scene disappears. I found that clicking on the summoner token makes the eidolon token reappear. It has to be done each time Foundry loads. It doesn't seem to be a major problem yet, but how can I stop this behavior?

I'm using Foundry v10.286 and Pathfinder 2E v4.1.3.

**Comment by trioderegion** [comment]
Hey, I'm a bit confused by the issue you are reporting. Is an "eidolon" token something special? Also, could this be part of the new vision system where the controlling actor is the only one that can see the token?

**Comment by Armandeus66** [comment]
Hi.
It is a regular token of a character type actor sheet. The actor is the
"pet" of a summoner PC actor. I'm not sure how the rule system links the
two.
It is not a vision issue. I am looking at the tokens as the GM on a scene
with default settings for lighting and vision.
The summoner PC's token is on the scene grid, but the pet is not, until I
click on the summoner token, which makes the pet token appear.
This happens every time I load Foundry, and on two scenes (the second with
lighting and so on) where these two actors have tokens placed.
The eidolon actor was created using the semi-official Companion Compendium
module.
This behavior started after I began using your module.

2022年10月15日(土) 1:49 trioderegion ***@***.***>:

**Comment by trioderegion** [comment]
Could it be that the pet token does not have vision enabled? so when you dont have any tokens selected, you are only seeing your character's vision?

**Comment by Armandeus66** [comment]
I am doing all this as the GM, not the player. I am also doing it on a
scene with token vision not enabled and one enabled with the same result.

2022年10月21日(金) 1:26 trioderegion ***@***.***>:

**Comment by trioderegion** [comment]
Apologies for the back and forth, just trying to get a handle on the situation ❤️ .

After you have summoned the token via warpgate, if you disable warpgate, does the issue persist?

**Comment by Armandeus66** [comment]
No problem.
This is before I summon anything using Warpgate. The summoned token
(eidolon) was already on the scene. Neither I nor the player has used
Warpgate. The player hasn't logged in since I installed the module.
I disabled Warpgate and the problem persists. I think I installed Warpgate
as a dependency for some other module. Now I can't remember which one.

2022年10月21日(金) 2:21 trioderegion ***@***.***>:

**Comment by trioderegion** [comment]
Ok, this is starting to make more sense.

Can you try disabling *all* other modules? I feel like there is some sort of module or system operation going on that is purposefully hiding that token under certain conditions.

**Comment by Armandeus66** [comment]
Warp Gate is required by [PF2e Animation Macros](https://github.com/MrVauxs/pf2e-jb2a-macros).

I don't know why, but it seems I no longer have this problem even if Warp Gate is enabled. I hope that means something fixed it (a module update?).

**Comment by trioderegion** [comment]
If this issue pops back up, feel free to re-open this ticket 😃
