### ISSUE TITLE
Warpgate.revert not reverting changes in Foundry v10.288 D&D 2.0.3 using Warpgate 1.14.0

### ISSUE THREAD

**Issue by Tatonker** [trioderegion/warpgate#81]
Hi,
[fvtt-Macro-reduce.zip](https://github.com/trioderegion/warpgate/files/9796938/fvtt-Macro-reduce.zip)

Per our conversation on Discord, I am not able to revert changes made to a token, either through the removal of the active effect that the mutations are tied to, the console or via separate macros. I've attached the 2 macros for your review.

The feature (with the macro called via the active effect application / removal) used to work in Foundry v9 but I've not had course to test these macros out in v10 until now.

Thanks for your time,

Tatonker

**Comment by trioderegion** [comment]
This macro is using v9 syntax (`data` instead of `system`). Currently, warpgate will fail to diff this data properly. I am going to see if I can shim this data for compatibility, but in the short term, updating to v10's datapaths will get this working again.
