### ISSUE TITLE
spawn rotation wrong!

### ISSUE THREAD

**Issue by EternalRider** [trioderegion/warpgate#97]
![image](https://user-images.githubusercontent.com/46736326/201739457-3321aa77-0679-4f26-8dc4-5f5f65b7a4c6.png)
![image](https://user-images.githubusercontent.com/46736326/201739384-01b40180-4206-4a36-8e55-6e8f01e2e7ff.png)

When multiple tokens are spawned continuously, the update data will accumulate, which is wrong.

**Comment by trioderegion** [comment]
🤣 haaa, great catch.

I was surprised to see "no issues" after restructuring how the update data was used (accumulation vs reset).  Makes total sense, and many thanks for the initial triage!
