### ISSUE TITLE
HTML in select options

### ISSUE THREAD

**Issue by MrVauxs** [trioderegion/warpgate#99]
As a continuation of #75, attempting to input HTML into `type: select` `options` returns wonky HTML due to it being simultaneously the value and the innerHTML of the option.

It would be nice to be able to put HTML in there, like for example adding the creature level `float`ing to the right.
```js
{
	type: "select",
	label: game.i18n.localize("pf2e-jb2a-macros.macro.summoning.player.creature"),
	options: packs.map(x => `${x.name} <span>(level ${x.level})</span>`),
},
```

**Comment by trioderegion** [comment]
[complex_select.webm](https://user-images.githubusercontent.com/14878515/213943484-e1380a1d-dcce-4c0b-93c2-c7f679def44a.webm)
